sudo: true

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.0
    - php: nightly

before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - phpunit
